#pragma once
#include "CTkObList.h"
#include <wtypes.h>
namespace FFXI {
	namespace CYy { class CMoResource; class CYyResourceFile; }
	namespace CTk {
		class CTkNode;
		class CTkMenuData;
		class CTkMenuCtrlData;
		class _49SubList;
		class CTkPrimitiveMenu;
		class CYkWndPartyList;
		class CTkDrawMessageWindow;
		class CTkDrawMessageWindow2;
		class CTkTarget;
		class CTkQueryWindow;
		class TKRECT;
		class CTkMenuMng {
		public:
			~CTkMenuMng();
			static const char* GetLanguageDependentMenu(int);
			static bool IsAreaWindow(unsigned short, CTkMenuCtrlData*, bool);
			static int SomeMapping(int);
			static void MarginComp(TKRECT*);
			void Init();
			void ZoneInit();
			void DeleteMenuAll();
			void CreateDrawMenu(const char*, bool, int);
			void DestroyDrawMenu(const char*);
			void DestroyDrawMenu(CTkMenuCtrlData*, char);
			void DeleteDrawMenu(CTkMenuCtrlData*);
			void OpenDrawMenu(CTkMenuCtrlData*);
			void CloseDrawMenu(CTkMenuCtrlData*, char, char, char, char);
			void AddDrawMenu(CTkMenuCtrlData*);
			void ActiveDrawMenu(CTkMenuCtrlData*, char);
			void CleanResName(char*, const char*);
			void FrameLoad(CYy::CYyResourceFile***, int);
			void GetWinCoefficient(float*, float*);
			void InitDraw();
			void EndDraw();
			void OnCalc();
			void OnDraw();
			void OnLButtonDown();
			void OnLButtonUp();
			void OnRButtonDown();
			void OnRButtonUp();
			void OnMButtonUp();
			void OnKeyDown(int);
			void OnPhaseCtrl();
			void OnMenuSwitchCtrl(int);
			CTkMenuCtrlData* GetCurMCD();
			void SetCurMCD(CTkMenuCtrlData*);
			void RemoveMCD(CTkMenuCtrlData*);
			bool IsEnableCreateDrawMenu(char*);
			bool HaveActiveWindow();
			void SetHideMode(char);
			int GetHideMode();
			bool IsHideMode();
			bool IsNoWindow();
			bool IsCurrentWindow(CTkMenuCtrlData*);
			bool IsActiveBlink(CTkMenuCtrlData*);
			CTkMenuCtrlData* GetDrawNext(CTkNode**);
			CTkMenuCtrlData* GetDrawPrev(CTkNode**);
			CTkMenuData* GetResourceMenu(char*);
			CTkMenuCtrlData* GetFromMCDList(char*);
			CTkMenuCtrlData* SearchCurMCD();
			void SetMenuPhase(int, int);
			float Get84(bool);
			float Get88(bool);
			void GetSomePosition(tagPOINT*, char, bool);
			CTkObList MCDList;
			CTkObList ResourceMenuList;
			CTkObList ObList3;
			CTkMenuCtrlData* CurMCD;
			CTkMenuCtrlData* PrevMCD;
			char field_59;
			char field_5A;
			char field_5B;
			CTkMenuCtrlData* field_5C;
			unsigned char field_60;
			char field_61;
			char field_62;
			char field_63;
			int field_64;
			char field_68;
			char field_69;
			char field_6A;
			char field_6B;
			unsigned short field_6C;
			char field_6E;
			char field_6F;
			char field_70;
			char field_71;
			char field_72;
			char field_73;
			char field_74;
			char field_75;
			char field_76;
			char field_77;
			int field_78;
			short field_7C;
			short field_7E;
			short UIXRes;
			short UIYRes;
			float field_84;
			float field_88;
			CTkDrawMessageWindow* LogWindow;
			CYkWndPartyList* PartyList;
			CTkTarget* TargetWindow;
			CTkQueryWindow* QueryWindow;
			CTkDrawMessageWindow2* LogWindow2;
			int field_A0;
			int field_A4;
			short field_A8;
			char field_AA;
			char field_AB;
			char field_AC;
			char field_AD;
			char field_AE;
			char field_AF;
			short field_B0;
			char field_B2;
			char field_B3;
			char HideMode;
			char field_B5;
			char field_B6;
			char field_B7;
			CYy::CYyResourceFile** field_B8;
			_49SubList*** field_BC;
		};
	}
}