#pragma once
#include "StorageListObject.h"
#include "WMatrix.h"
namespace FFXI {
	namespace CYy {
		class CMoCameraTask;
		class CYyCamMng2 : public StorageListObject {
		public:
			const static CYyClass CYyCamMng2Class;
			virtual const CYyClass* GetRuntimeClass() override final;
			virtual void VObj2(int*) override final;
			static void InitCameraManager();
			static void SetSomeValues(char, char, int);
			static void ResetCameraInitTimer();
			static void GetSomeVecs(D3DXVECTOR3*, D3DXVECTOR3*);
			static char SomeByte1;
			static char SomeByte2;
			static int SomeDword1;
			static int CameraInitTimer;
			static CMoCameraTask* CurrentCameraTask;
			CYyCamMng2();
			~CYyCamMng2();
			void Init();
			void SomeInit();
			void Update();
			void SetPos(D3DXVECTOR3*);
			void SetAt(D3DXVECTOR3*);
			bool Check();
			FFXI::Math::WMatrix* MakeMatrix();
			FFXI::Math::WMatrix* GetView();
			FFXI::Math::WMatrix field_4;
			D3DXVECTOR3 Position;
			D3DXVECTOR3 field_50;
			float field_5C;
			D3DXVECTOR3 field_60;
			D3DXVECTOR3 field_6C;
			float field_78;
			float field_7C;
			float field_80;
			float field_84;
			char field_88;
			char field_89;
			char field_8A;
			char field_8B;
			D3DXVECTOR3 field_8C;
			D3DXVECTOR3 field_98;
			float field_A4;
			D3DXVECTOR3 field_A8;
			float field_B4;
			float field_B8;
			char field_BC;
			char field_BD;
			char field_BE;
			char field_BF;
			char field_C0;
			char field_C1;
			char field_C2;
			char field_C3;
			char field_C4;
			char field_C5;
			char field_C6;
			char field_C7;
			char field_C8;
			char field_C9;
			char field_CA;
			char field_CB;
			char field_CC;
			char field_CD;
			char field_CE;
			char field_CF;
			char field_D0;
			char field_D1;
			char field_D2;
			char field_D3;
			char field_D4;
			char field_D5;
			char field_D6;
			char field_D7;
			char field_D8;
			char field_D9;
			char field_DA;
			char field_DB;
			char field_DC;
			char field_DD;
			char field_DE;
			char field_DF;
			char field_E0;
			char field_E1;
			char field_E2;
			char field_E3;
			char field_E4;
			char field_E5;
			char field_E6;
			char field_E7;
			char field_E8;
			char field_E9;
			char field_EA;
			char field_EB;
			char field_EC;
			char field_ED;
			char field_EE;
			char field_EF;
			char field_F0;
			char field_F1;
			char field_F2;
			char field_F3;
			char field_F4;
			char field_F5;
			char field_F6;
			char field_F7;
			char field_F8;
			char field_F9;
			char field_FA;
			char field_FB;
			char field_FC;
			char field_FD;
			char field_FE;
			char field_FF;
			char field_100;
			char field_101;
			char field_102;
			char field_103;
			char field_104;
			char field_105;
			char field_106;
			char field_107;
			char field_108;
			char field_109;
			char field_10A;
			char field_10B;
			char field_10C;
			char field_10D;
			char field_10E;
			char field_10F;
			char field_110;
			char field_111;
			char field_112;
			char field_113;
			char field_114;
			char field_115;
			char field_116;
			char field_117;
		};
	}
}