#pragma once
namespace FFXI {
	namespace Constants {
		namespace Enums {
			enum class GPUVendorID {
				NVIDIA = 0x10DE,
				AMD = 0x1002,
				Intel = 0x8086
			};

            enum class CPUVendorID {
                Unknown = 0,
                Intel = 1,
                AMD = 2
            };

			enum LanguageCode {
				Japanese = 0,
				English = 1,
				French = 2,
				German = 3
			};

            enum class WIN_MODE {
                Fullscreen = 0,
                Windowed = 1,
                BorderlessWindowed = 2,
                BorderlessFullscreen = 3
            };
            enum class LanguageDependentDats {
                TEX_General = 0,
                TEX_1 = 1,
                CharSelectRaceGender = 2,
                CharSelectText = 3,
                JobFullNames = 4,
                Errors = 7,
                LobbyHelpText = 8,
                VariousHelpText = 10,
                MenuText2 = 12,
                MenuText1 = 13,
                MiscMenuText = 14,
                MENU_MissionQuest = 0x57,
                MENU_Unk1 = 0x58
            };

			enum LanguageDependentMenus {
				LDM_Frames = 0,
				LDM_ComWin = 1,
				LDM_Resyn = 2,
				LDM_Compass = 3,
				LDM_ScItem = 4,
				LDM_Key1Top = 5,
				LDM_JobcSel = 6,
				LDM_Prty5 = 7,
				LDM_LAST = 8
			};

			enum StrTables {
				XIStr_0 = 0,
				XIStr_CharSelectText = 1,
				XIStr_JobShortNames = 2,
				XIStr_JobFullNames = 3,
				XIStr_ZoneShortNames = 4,
				XIStr_ZoneFullNames = 5,
				XIStr_CharSelectRaceGender = 6,
				XIStr_Errors = 7,
				XIStr_LobbyHelpText = 8,
				XIStr_9 = 9,
				XIStr_VariousHelpText = 10,
				XIStr_11 = 11,
				XIStr_MiscMenuText = 12,
				XIStr_Menu1 = 13,
				XIStr_Menu2 = 14,
				XIStr_15 = 15,
				XIStr_16 = 16,
				XIStr_17 = 17,
				XIStr_18 = 18,
				XIStr_19 = 19,
				XIStr_20 = 20,
				XIStr_21 = 21,
				XIStr_22 = 22,
				XIStr_23 = 23,
				XIStr_GearSlotNames = 24,
				XIStr_OdinFightMobs = 25,
				XIStr_26 = 26,
				XIStr_27 = 27,
				XIStr_28 = 28,
				XIStr_29 = 29,
				XIStr_30 = 30,
				XIStr_31 = 31,
				XIStr_LASTDMSG = 28,
				XIStr_LAST = 32
			};

			enum AudioEncoding {
				Encoding0 = 0,
				Encoding1 = 1,
				Encoding2 = 2,
				ATRAC3 = 3
			};

			enum FontQuality {
				FONT_COMPRESSED = 0,
				FONT_UNCOMPRESSED = 1,
				FONT_HQ = 2
			};

			enum KEYTYPE {
				KEYTYPE_PAD_R_UP = 17,
				KEYTYPE_PAD_L1_COPY1 = 20,
				KEYTYPE_PAD_R2 = 24,
				KEYTYPE_PAD_R1 = 30,
				KEYTYPE_PAD_L1 = 31,
				KEYTYPE_PAD_R_UP_COPY1 = 34,
				KEYTYPE_PAD_R1_COPY1 = 36,
				KEYTYPE_PAD_R_LEFT = 37,
				KEYTYPE_PAD_SELECT = 38,
				KEYTYPE_PAD_L_UP = 43,
				KEYTYPE_PAD_L_DOWN = 44,
				KEYTYPE_PAD_L_RIGHT = 45,
				KEYTYPE_PAD_L_LEFT = 46,
				KEYTYPE_PAD_SELECT_COPY1 = 47,
				KEYTYPE_PAD_R_RIGHT = 147,
				KEYTYPE_PAD_R_DOWN = 148,
				KEYTYPE_PAD_R2_COPY1 = 133,
				KEYTYPE_PAD_L2 = 134,
				KEYTYPE_MOUSE_LBUTTON = 139,
				KEYTYPE_MOUSE_RBUTTON = 140,
				KEYTYPE_MOUSE_MBUTTON = 150
			};

			enum TRGTYPE {
				TRGTYPE_0 = 0,
				TRGTYPE_1 = 1,
				TRGTYPE_2 = 2,
				TRGTYPE_3 = 3,
				TRGTYPE_4 = 4,
				TRGTYPE_5 = 5,
			};

			enum SoundCommand {
				_0 = 0,
				_1 = 1,
				PlaySep = 2,
				PanDirect = 3,
				VolumeDirect = 4,
				SEFadeOut = 5,
				_6 = 6,
				PlaySoundFromDisk = 7,
				VolumeTranslate = 8,
				MusicFadeOut = 9,
				SetReplayPoint = 10,
				ClearAudioPos = 11,
				SetStartPoint = 12,
				_13 = 13
			};

			enum TkDrawType {
				TKDraw_Frame = 0,
				TKDraw_Button = 1,
				TKDraw_Cursol = 2
			};
			enum ResourceType {
				Terminate = 0,
				Rmp,
				Rmw,
				Directory,
				Bin,
				Generater,
				Camera,
				Scheduler,
				Mtx,
				Tim,
				Texinfo,
				Vum,
				Om1,
				Fileinfo,
				Anm,
				Rsd,
				Unknown_2,
				Osm,
				Skd,
				Mtd,
				Mld,
				Mlt,
				Mws,
				Mod_1,
				Tim2,
				Keyframe,
				Bmp,
				Bmp2,
				Mzb,
				Mmd,
				Mep,
				D3m,
				D3s,
				D3a,
				Distprog,
				Vulineprog,
				Ringprog,
				D3b,
				Asn,
				Mot,
				Skl,
				Sk2,
				Os2,
				Mo2,
				Psw,
				Wsd,
				Mmb,
				Weather,
				Meb,
				Msb,
				Med,
				Msh,
				Ysh,
				Mbp,
				Rid,
				Wd,
				Bgm,
				Lfd,
				Lfe,
				Esh,
				Sch,
				Sep,
				Vtx,
				Lwo,
				Rme,
				Elt,
				Rab,
				Mtt,
				Mtb,
				Cib,
				Tlt,
				Pointlightprog,
				Mgd,
				Mgb,
				Sph,
				Bmd,
				Qif,
				Qdt,
				Mif,
				Mdt,
				Sif,
				Sdt,
				Acd,
				Acb,
				Afb,
				Aft,
				Wwd,
				Nullprog,
				Spw,
				Fud,
				DisgregaterProg,
				Smt,
				Damvalueprog,
				Bp,
				Max_0
			};

            enum class ElemType {
                Base =          0,
                Dist =          1,
                PointLight =    11,
                Lfd =           12,
                Sound =         14,
                D3b =           15
            };
            
			enum class MEM_MODE {
				Upper = 0,
				Lower = 1,
				Elem = 2,
				Work = 3,
				Ex = 4,
				Load = 5,
				Menu = 6,
			};

            enum Zone {
                Unknown = 0,
                Phanauet_Channel = 1,
                Carpenters_Landing = 2,
                Manaclipper = 3,
                Bibiki_Bay = 4,
                Uleguerand_Range = 5,
                Bearclaw_Pinnacle = 6,
                Attohwa_Chasm = 7,
                Boneyard_Gully = 8,
                PsoXja = 9,
                The_Shrouded_Maw = 10,
                Oldton_Movalpolos = 11,
                Newton_Movalpolos = 12,
                Mineshaft_2716 = 13,
                Hall_of_Transference = 14,
                Abyssea_Konschtat = 15,
                Promyvion_Holla = 16,
                Spire_of_Holla = 17,
                Promyvion_Dem = 18,
                Spire_of_Dem = 19,
                Promyvion_Mea = 20,
                Spire_of_Mea = 21,
                Promyvion_Vahzl = 22,
                Spire_of_Vahzl = 23,
                Lufaise_Meadows = 24,
                Misareaux_Coast = 25,
                Tavnazian_Safehold = 26,
                Phomiuna_Aqueducts = 27,
                Sacrarium = 28,
                Riverne_Site_B01 = 29,
                Riverne_Site_A01 = 30,
                Monarch_Linn = 31,
                Sealions_Den = 32,
                AlTaieu = 33,
                Grand_Palace_of_HuXzoi = 34,
                The_Garden_of_RuHmet = 35,
                Empyreal_Paradox = 36,
                Temenos = 37,
                Apollyon = 38,
                Dynamis_Valkurm = 39,
                Dynamis_Buburimu = 40,
                Dynamis_Qufim = 41,
                Dynamis_Tavnazia = 42,
                Diorama_Abdhaljs_Ghelsba = 43,
                Abdhaljs_Isle_Purgonorgo = 44,
                Abyssea_Tahrongi = 45,
                Open_sea_route_to_Al_Zahbi = 46,
                Open_sea_route_to_Mhaura = 47,
                Al_Zahbi = 48,
                Aht_Urhgan_Whitegate = 50,
                Wajaom_Woodlands = 51,
                Bhaflau_Thickets = 52,
                Nashmau = 53,
                Arrapago_Reef = 54,
                Ilrusi_Atoll = 55,
                Periqia = 56,
                Talacca_Cove = 57,
                Silver_Sea_Route_to_Nashmau = 58,
                Silver_Sea_Route_to_Al_Zahbi = 59,
                The_Ashu_Talif = 60,
                Mount_Zhayolm = 61,
                Halvung = 62,
                Lebros_Cavern = 63,
                Navukgo_Execution_Chamber = 64,
                Mamook = 65,
                Mamool_Ja_Training_Grounds = 66,
                Jade_Sepulcher = 67,
                Aydeewa_Subterrane = 68,
                Leujaoam_Sanctum = 69,
                Chocobo_Circuit = 70,
                The_Colosseum = 71,
                Alzadaal_Undersea_Ruins = 72,
                Zhayolm_Remnants = 73,
                Arrapago_Remnants = 74,
                Bhaflau_Remnants = 75,
                Silver_Sea_Remnants = 76,
                Nyzul_Isle = 77,
                Hazhalm_Testing_Grounds = 78,
                Caedarva_Mire = 79,
                Southern_San_dOria_S = 80,
                East_Ronfaure_S = 81,
                Jugner_Forest_S = 82,
                Vunkerl_Inlet_S = 83,
                Batallia_Downs_S = 84,
                La_Vaule_S = 85,
                Everbloom_Hollow = 86,
                Bastok_Markets_S = 87,
                North_Gustaberg_S = 88,
                Grauberg_S = 89,
                Pashhow_Marshlands_S = 90,
                Rolanberry_Fields_S = 91,
                Beadeaux_S = 92,
                Ruhotz_Silvermines = 93,
                Windurst_Waters_S = 94,
                West_Sarutabaruta_S = 95,
                Fort_Karugo_Narugo_S = 96,
                Meriphataud_Mountains_S = 97,
                Sauromugue_Champaign_S = 98,
                Castle_Oztroja_S = 99,
                West_Ronfaure = 100,
                East_Ronfaure = 101,
                La_Theine_Plateau = 102,
                Valkurm_Dunes = 103,
                Jugner_Forest = 104,
                Batallia_Downs = 105,
                North_Gustaberg = 106,
                South_Gustaberg = 107,
                Konschtat_Highlands = 108,
                Pashhow_Marshlands = 109,
                Rolanberry_Fields = 110,
                Beaucedine_Glacier = 111,
                Xarcabard = 112,
                Cape_Teriggan = 113,
                Altepa_Eastern_Desert = 114,
                West_Sarutabaruta = 115,
                East_Sarutabaruta = 116,
                Tahrongi_Canyon = 117,
                Buburimu_Peninsula = 118,
                Meriphataud_Mountains = 119,
                Sauromugue_Champaign = 120,
                Sanctuary_of_ZiTah = 121,
                RoMaeve = 122,
                Yuhtunga_Jungle = 123,
                Yhoator_Jungle = 124,
                Altepa_Western_Desert = 125,
                Qufim_Island = 126,
                Behemoths_Dominion = 127,
                Valley_of_Sorrows = 128,
                Ghoyus_Reverie = 129,
                RuAun_Gardens = 130,
                Mordion_Gaol = 131,
                Abyssea_La_Theine = 132,
                Lobby = 133,
                Dynamis_Beaucedine = 134,
                Dynamis_Xarcabard = 135,
                Beaucedine_Glacier_S = 136,
                Xarcabard_S = 137,
                Castle_Zvahl_Baileys_S = 138,
                Horlais_Peak = 139,
                Ghelsba_Outpost = 140,
                Fort_Ghelsba = 141,
                Yughott_Grotto = 142,
                Palborough_Mines = 143,
                Waughroon_Shrine = 144,
                Giddeus = 145,
                Balgas_Dais = 146,
                Beadeaux = 147,
                Qulun_Dome = 148,
                Davoi = 149,
                Monastic_Cavern = 150,
                Castle_Oztroja = 151,
                Altar_Room = 152,
                Boyahda_Tree = 153,
                Dragons_Aery = 154,
                Castle_Zvahl_Keep_S = 155,
                Throne_Room_S = 156,
                Delkfutts_Middle_Tower = 157,
                Delkfutts_Upper_Tower = 158,
                Temple_of_Uggalepih = 159,
                Den_of_Rancor = 160,
                Castle_Zvahl_Baileys = 161,
                Castle_Zvahl_Keep = 162,
                Sacrificial_Chamber = 163,
                Garlaige_Citadel_S = 164,
                Throne_Room = 165,
                Ranguemont_Pass = 166,
                Bostaunieux_Oubliette = 167,
                Chamber_of_Oracles = 168,
                Toraimarai_Canal = 169,
                Full_Moon_Fountain = 170,
                Crawlers_Nest_S = 171,
                Zeruhn_Mines = 172,
                Korroloka_Tunnel = 173,
                Kuftal_Tunnel = 174,
                The_Eldieme_Necropolis_S = 175,
                Sea_Serpent_Grotto = 176,
                VeLugannon_Palace = 177,
                Shrine_of_RuAvitau = 178,
                Stellar_Fulcrum = 179,
                LaLoff_Amphitheater = 180,
                The_Celestial_Nexus = 181,
                Walk_of_Echoes = 182,
                The_Last_Stand = 183,
                Delkfutts_Lower_Tower = 184,
                Dynamis_San_dOria = 185,
                Dynamis_Bastok = 186,
                Dynamis_Windurst = 187,
                Dynamis_Jeuno = 188,
                King_Ranperres_Tomb = 190,
                Dangruf_Wadi = 191,
                Horutoto_Inner_Ruins = 192,
                Ordelles_Caves = 193,
                Outer_Horutoto_Ruins = 194,
                Eldieme_Necropolis = 195,
                Gusgen_Mines = 196,
                Crawlers_Nest = 197,
                Maze_of_Shakhrami = 198,
                Garlaige_Citadel = 200,
                Cloister_of_Gales = 201,
                Cloister_of_Storms = 202,
                Cloister_of_Frost = 203,
                FeiYin = 204,
                Ifrits_Cauldron = 205,
                QuBia_Arena = 206,
                Cloister_of_Flames = 207,
                Quicksand_Caves = 208,
                Cloister_of_Tremors = 209,
                Cloister_of_Tides = 211,
                Gustav_Tunnel = 212,
                Labyrinth_of_Onzozo = 213,
                Abyssea_Attohwa = 215,
                Abyssea_Misareaux = 216,
                Abyssea_Vunkerl = 217,
                Abyssea_Altepa = 218,
                Ferry_between_Mhaura__Selbina = 220,
                Ferry_between_Selbina__Mhaura = 221,
                Provenance = 222,
                Airship_from_San_dOria_to_Jeuno = 223,
                Airship_from_Bastok_to_Jeuno = 224,
                Airship_from_Windurst_to_Jeuno = 225,
                Airship_from_Kazham_to_Jeuno = 226,
                Ferry_between_Mhaura__Selbina_Pirates = 227,
                Ferry_between_Selbina__Mhaura_Pirates = 228,
                Southern_San_dOria = 230,
                Northern_San_dOria = 231,
                Port_San_dOria = 232,
                Chateau_dOraguille = 233,
                Bastok_Mines = 234,
                Bastok_Markets = 235,
                Port_Bastok = 236,
                Metalworks = 237,
                Windurst_Waters = 238,
                Windurst_Walls = 239,
                Port_Windurst = 240,
                Windurst_Woods = 241,
                Heavens_Tower = 242,
                Ru_Lude_Gardens = 243,
                Upper_Jeuno = 244,
                Lower_Jeuno = 245,
                Port_Jeuno = 246,
                Rabao = 247,
                Selbina = 248,
                Mhaura = 249,
                Kazham = 250,
                Hall_of_the_Gods = 251,
                Norg = 252,
                Abyssea_Uleguerand = 253,
                Abyssea_Grauberg = 254,
                Abyssea_Empyreal_Paradox = 255,
                Western_Adoulin = 256,
                Eastern_Adoulin = 257,
                Rala_Waterways = 258,
                Rala_Waterways_U = 259,
                Yahse_Hunting_Grounds = 260,
                Ceizak_Battlegrounds = 261,
                Foret_de_Hennetiel = 262,
                Yorcia_Weald = 263,
                Yorcia_Weald_U = 264,
                Morimar_Basalt_Fields = 265,
                Marjami_Ravine = 266,
                Kamihr_Drifts = 267,
                Sih_Gates = 268,
                Moh_Gates = 269,
                Cirdas_Caverns = 270,
                Cirdas_Caverns_U = 271,
                Dho_Gates = 272,
                Woh_Gates = 273,
                Outer_RaKaznar = 274,
                Outer_RaKaznar_U = 275,
                RaKaznar_Inner_Court = 276,
                Mog_Garden = 280,
                Silver_Knife = 283,
                Celennia_Wexworth_Memorial_Library = 284,
                Feretory = 285
            };

            enum class FsConfigSubjects {
                Subject0 = 0,
                Subject1 = 1,
                Subject2 = 2,
                Subject3 = 3,
                Subject4 = 4,
                Subject5 = 5,
                Subject6 = 6,
                Subject7 = 7,
                Subject8 = 8,
                Subject9 = 9,
                Subject10 = 10,
                Subject11 = 11,
                Subject12 = 12,
                Subject13 = 13,
                Subject14 = 14,
                Subject15 = 15,
                Subject16 = 16,
                Subject17 = 17,
                Subject18 = 18,
                Subject19 = 19,
                Subject20 = 20,
                Subject21 = 21,
                Subject22 = 22,
                Subject23 = 23,
                Subject24 = 24,
                Subject25 = 25,
                Subject26 = 26,
                Subject27 = 27,
                Subject28 = 28,
                Subject29 = 29,
                Subject30 = 30,
                Subject31 = 31,
                Subject32 = 32,
                Subject33 = 33,
                Subject34 = 34,
                Subject35 = 35,
                Subject36 = 36,
                Subject37 = 37,
                Subject38 = 38,
                Subject39 = 39,
                Subject40 = 40,
                Subject41 = 41,
                Subject42 = 42,
                Subject43 = 43,
                Subject44 = 44,
                Subject45 = 45,
                Subject46 = 46,
                Subject47 = 47,
                Subject48 = 48,
                Subject49 = 49,
                Subject50 = 50,
                Subject51 = 51,
                Subject52 = 52,
                Subject53 = 53,
                Subject54 = 54,
                Subject55 = 55,
                Subject56 = 56,
                Subject57 = 57,
                Subject58 = 58,
                Subject59 = 59,
                Subject60 = 60,
                Subject61 = 61,
                Subject62 = 62,
                Subject63 = 63,
                Subject64 = 64,
                Subject65 = 65,
                Subject66 = 66,
                Subject67 = 67,
                Subject68 = 68,
                Subject69 = 69,
                Subject70 = 70,
                Subject71 = 71,
                Subject72 = 72,
                Subject73 = 73,
                Subject74 = 74,
                Subject75 = 75,
                Subject76 = 76,
                Subject77 = 77,
                Subject78 = 78,
                Subject79 = 79,
                Subject80 = 80,
                Subject81 = 81,
                Subject82 = 82,
                Subject83 = 83,
                Subject84 = 84,
                Subject85 = 85,
                Subject86 = 86,
                Subject87 = 87,
                Subject88 = 88,
                Subject89 = 89,
                Subject90 = 90,
                Subject91 = 91,
                Subject92 = 92,
                Subject93 = 93,
                Subject94 = 94,
                Subject95 = 95,
                Subject96 = 96,
                Subject97 = 97,
                Subject98 = 98,
                Subject99 = 99,
                Subject100 = 100,
                Subject101 = 101,
                Subject102 = 102,
                Subject103 = 103,
                Subject104 = 104,
                Subject105 = 105,
                Subject106 = 106,
                Subject107 = 107,
                Subject108 = 108,
                Subject109 = 109,
                Subject110 = 110,
                Subject111 = 111,
                Subject112 = 112,
                Subject113 = 113,
                Subject114 = 114,
                Subject115 = 115,
                Subject116 = 116,
                Subject117 = 117,
                Subject118 = 118,
                Subject119 = 119,
                Subject120 = 120,
                Subject121 = 121,
                Subject122 = 122,
                Subject123 = 123,
                Subject124 = 124,
                Subject125 = 125,
                Subject126 = 126,
                Subject127 = 127,
                Subject128 = 128,
                Subject129 = 129,
                Subject130 = 130,
                Subject131 = 131,
                Subject132 = 132,
                Subject133 = 133,
                Subject134 = 134,
                Subject135 = 135,
                Subject136 = 136,
                Subject137 = 137,
                Subject138 = 138,
                Subject139 = 139,
                Subject140 = 140,
                Subject141 = 141,
                Subject142 = 142,
                Subject143 = 143,
                Subject144 = 144,
                Subject145 = 145,
                Subject146 = 146,
                Subject147 = 147,
                Subject148 = 148,
                Subject149 = 149,
                Subject150 = 150,
                Subject151 = 151,
                Subject152 = 152,
                Subject153 = 153,
                Subject154 = 154,
                Subject155 = 155,
                Subject156 = 156,
                Subject157 = 157,
                Subject158 = 158,
                Subject159 = 159,
                Subject160 = 160,
                Subject161 = 161,
                Subject162 = 162,
                Subject163 = 163,
                Subject164 = 164,
                Subject165 = 165,
                Subject166 = 166,
                Subject167 = 167,
                Subject168 = 168,
                Subject169 = 169,
                Subject170 = 170,
                Subject171 = 171,
                Subject172 = 172,
                Subject173 = 173,
                Subject174 = 174,
                TitleScreenSong = 175,
                Subject176 = 176,
                Subject177 = 177,
                Subject178 = 178,
                Subject179 = 179,
                Subject180 = 180,
                Subject181 = 181,
                Subject182 = 182,
                Subject183 = 183,
                Subject184 = 184,
                Subject185 = 185,
                Subject186 = 186,
                Subject187 = 187,
                Subject188 = 188,
                Subject189 = 189,
                Subject190 = 190,
                Subject191 = 191,
                Subject192 = 192,
                Subject193 = 193,
                Subject194 = 194,
                Subject195 = 195,
                Subject196 = 196,
                Subject197 = 197,
                Subject198 = 198,
                Subject199 = 199,
                Subject200 = 200,
                Subject201 = 201,
                Subject202 = 202,
                Subject203 = 203,
                Subject204 = 204,
                Subject205 = 205,
                Subject206 = 206,
                count
            };

            enum LobbyOutgoingOpcodes {
                LOBBY_OUT_LOGIN              = 0x26,
                LOBBY_OUT_REQUEST_CONTENTIDS = 0x1F,
                LOBBY_OUT_REQUEST_WORLDLIST  = 0x24
            };

            enum LobbyIncomingOpcodes {
                LOBBY_IN_ERROR      = 0x04,
                LOBBY_IN_LOGIN_GOOD = 0x05,
                LOBBY_IN_CHARLIST   = 0x20,
                LOBBY_IN_WORLDLIST  = 0x23
            };
		}
	}
}